# Generated by Django 4.1.5 on 2023-01-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.CharField(max_length=200)),
                ('blog_title', models.CharField(max_length=200)),
                ('blog_content', models.CharField(max_length=30000)),
                ('blog_summary', models.CharField(max_length=30000)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField()),
                ('comment_author', models.CharField(max_length=200)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('comment_type', models.CharField(max_length=20)),
            ],
        ),
    ]
